INSERT INTO cities (state_id, name) VALUES
('EC01','Cuenca'),
('EC01','Giron'),
('EC01','Gualaceo'),
('EC01','Nabon'),
('EC01','Paute'),
('EC01','Pucara'),
('EC01','San Fernando'),
('EC01','Santa Isabel'),
('EC01','Sigsig'),
('EC01','Oña'),
('EC01','Chordeleg'),
('EC01','El Pan'),
('EC01','Sevilla De Oro'),
('EC01','Guachapala'),
('EC01','Camilo Ponce Enriquez'),
('EC02','Guaranda'),
('EC02','Chillanes'),
('EC02','Chimbo'),
('EC02','Echeandia'),
('EC02','San Miguel'),
('EC02','Caluma'),
('EC02','Las Naves'),
('EC03','Azogues'),
('EC03','Biblián'),
('EC03','Cañar'),
('EC03','La Troncal'),
('EC03','El Tambo'),
('EC03','Deleg'),
('EC03','Suscal'),
('EC04','Tulcán'),
('EC04','Bolivar'),
('EC04','Espejo'),
('EC04','Mira'),
('EC04','Montufar'),
('EC04','San Pedro De Huaca'),
('EC05','Latacunga'),
('EC05','La Maná'),
('EC05','Pangua'),
('EC05','Pujili'),
('EC05','Salcedo'),
('EC05','Saquisili'),
('EC05','Sigchos'),
('EC06','Riobamba'),
('EC06','Alausí'),
('EC06','Colta'),
('EC06','Chambo'),
('EC06','Chunchi'),
('EC06','Guamote'),
('EC06','Guano'),
('EC06','Pallatanga'),
('EC06','Penipe'),
('EC06','Cumanda'),
('EC07','Machala'),
('EC07','Arenillas'),
('EC07','Atahualpa'),
('EC07','Balsas'),
('EC07','Chilla'),
('EC07','El Guabo'),
('EC07','Huaquillas'),
('EC07','Marcabeli'),
('EC07','Pasaje'),
('EC07','Piñas'),
('EC07','Portovelo'),
('EC07','Santa Rosa'),
('EC07','Zaruma'),
('EC07','Las Lajas'),
('EC08','Esmeraldas'),
('EC08','Eloy Alfaro'),
('EC08','Muisne'),
('EC08','Quinindé'),
('EC08','San Lorenzo'),
('EC08','Atacames'),
('EC08','Rioverde'),
('EC08','La Concordia'),
('EC09','Guayaquil'),
('EC09','Alfredo Baquerizo Moreno'),
('EC09','Balao'),
('EC09','Balzar'),
('EC09','Colimes'),
('EC09','Daule'),
('EC09','Durán'),
('EC09','Empalme'),
('EC09','El Triunfo'),
('EC09','Milagro'),
('EC09','Naranjal'),
('EC09','Naranjito'),
('EC09','Palestina'),
('EC09','Pedro Carbo'),
('EC09','Samborondon'),
('EC09','Santa Lucia'),
('EC09','Salitre'),
('EC09','San Jacinto De Yaguachi'),
('EC09','Playas'),
('EC09','Simon Bolivar'),
('EC09','Crnel. Marcelino Maridueña'),
('EC09','Lomas De Sargentillo'),
('EC09','Nobol'),
('EC09','Gnral. Antonio Elizalde'),
('EC09','Isidro Ayora'),
('EC10','Ibarra'),
('EC10','Antonio Ante'),
('EC10','Cotacachi'),
('EC10','Otavalo'),
('EC10','Pimampiro'),
('EC10','San Miguel De Urcuqui'),
('EC11','Loja'),
('EC11','Calvas'),
('EC11','Catamayo'),
('EC11','Celica'),
('EC11','Chaguarpamba'),
('EC11','Espindola'),
('EC11','Gonzanama'),
('EC11','Macara'),
('EC11','Paltas'),
('EC11','Puyango'),
('EC11','Saraguro'),
('EC11','Sozoranga'),
('EC11','Zapotillo'),
('EC11','Pindal'),
('EC11','Quilanga'),
('EC11','Olmedo'),
('EC12','Babahoyo'),
('EC12','Baba'),
('EC12','Montalvo'),
('EC12','Puebloviejo'),
('EC12','Quevedo'),
('EC12','Urdaneta'),
('EC12','Ventanas'),
('EC12','Vinces'),
('EC12','Palenque'),
('EC12','Buena Fe'),
('EC12','Valencia'),
('EC12','Mocache'),
('EC12','Quinsaloma'),
('EC13','Portoviejo'),
('EC13','Bolivar'),
('EC13','Chone'),
('EC13','El Carmen'),
('EC13','Flavio Alfaro'),
('EC13','Jipijapa'),
('EC13','Junin'),
('EC13','Manta'),
('EC13','Montecristi'),
('EC13','Pajan'),
('EC13','Pichincha'),
('EC13','Rocafuerte'),
('EC13','Santa Ana'),
('EC13','Sucre'),
('EC13','Tosagua'),
('EC13','24 De Mayo'),
('EC13','Pedernales'),
('EC13','Olmedo'),
('EC13','Puerto Lopez'),
('EC13','Jama'),
('EC13','Jaramijo'),
('EC13','San Vicente'),
('EC14','Morona'),
('EC14','Gualaquiza'),
('EC14','Limon Indanza'),
('EC14','Palora'),
('EC14','Santiago'),
('EC14','Sucua'),
('EC14','Huamboya'),
('EC14','San Juan Bosco'),
('EC14','Taisha'),
('EC14','Logroño'),
('EC14','Pablo Sexto'),
('EC14','Tiwintza'),
('EC15','Tena'),
('EC15','Archidona'),
('EC15','El Chaco'),
('EC15','Quijos'),
('EC15','Carlos Julio Arosemena Tola'),
('EC16','Pastaza'),
('EC16','Mera'),
('EC16','Santa Clara'),
('EC16','Arajuno'),
('EC17','Quito'),
('EC17','Cayambe'),
('EC17','Mejia'),
('EC17','Pedro Moncayo'),
('EC17','Rumiñahui'),
('EC17','San Miguel De Los Bancos'),
('EC17','Pedro Vicente Maldonado'),
('EC17','Puerto Quito'),
('EC18','Ambato'),
('EC18','Baños De Agua Santa'),
('EC18','Cevallos'),
('EC18','Mocha'),
('EC18','Patate'),
('EC18','Quero'),
('EC18','San Pedro De Pelileo'),
('EC18','Santiago De Pillaro'),
('EC18','Tisaleo'),
('EC19','Zamora'),
('EC19','Chinchipe'),
('EC19','Nangaritza'),
('EC19','Yacuambi'),
('EC19','Yantzaza'),
('EC19','El Pangui'),
('EC19','Centinela Del Condor'),
('EC19','Palanda'),
('EC19','Paquisha'),
('EC20','San Cristobal'),
('EC20','Isabela'),
('EC20','Santa Cruz'),
('EC21','Lago Agrio'),
('EC21','Gonzalo Pizarro'),
('EC21','Putumayo'),
('EC21','Shushufindi'),
('EC21','Sucumbios'),
('EC21','Cascales'),
('EC21','Cuyabeno'),
('EC22','Orellana'),
('EC22','Aguarico'),
('EC22','La Joya De Los Sachas'),
('EC22','Loreto'),
('EC23','Santo Domingo'),
('EC24','Santa Elena'),
('EC24','La Libertad'),
('EC24','Salinas');
