INSERT INTO countries (name, id) VALUES
('Afghanistán', 'AF'),
('Islas Åland', 'AX'),
('Albania', 'AL'),
('Algeria', 'DZ'),
('Samoa Americana', 'AS'),
('Andorra', 'AD'),
('Angola', 'AO'),
('Anguilla', 'AI'),
('Antárctica', 'AQ'),
('Antigua y Barbuda', 'AG'),
('Argentina', 'AR'),
('Armenia', 'AM'),
('Aruba', 'AW'),
('Australia', 'AU'),
('Austria', 'AT'),
('Azerbaiyán', 'AZ'),
('Bahamas', 'BS'),
('Bahrain', 'BH'),
('Bangladesh', 'BD'),
('Barbados', 'BB'),
('Bielorrusia', 'BY'),
('Bélgica', 'BE'),
('Belize', 'BZ'),
('Benín', 'BJ'),
('Bermuda', 'BM'),
('Bután', 'BT'),
('Bolivia', 'BO'),
('Bonaire', 'BQ'),
('Bosnia y Herzegovina', 'BA'),
('Botsuana', 'BW'),
('Isla Bouvet', 'BV'),
('Brasil', 'BR'),
('Territorio Británico del Océano Índico', 'IO'),
('Brunéi Darussalam', 'BN'),
('Bulgaria', 'BG'),
('Burkina Faso', 'BF'),
('Burundi', 'BI'),
('Camboya', 'KH'),
('Camerún', 'CM'),
('Canadá', 'CA'),
('Cabo Verde', 'CV'),
('Islas Caimán', 'KY'),
('República Centroafricana', 'CF'),
('Chad', 'TD'),
('Chile', 'CL'),
('China', 'CN'),
('Isla de Navidad', 'CX'),
('Islas Cocos', 'CC'),
('Colombia', 'CO'),
('Comoras', 'KM'),
('Congo', 'CG'),
('República Democrática del Congo', 'CD'),
('Islas Cook', 'CK'),
('Costa Rica', 'CR'),
('Costa de Marfil', 'CI'),
('Croacia', 'HR'),
('Cuba', 'CU'),
('Curazao', 'CW'),
('Chipre', 'CY'),
('República Checa', 'CZ'),
('Dinamarca', 'DK'),
('Djibouti', 'DJ'),
('Dominica', 'DM'),
('República Dominicana', 'DO'),
('Ecuador', 'EC'),
('Egipto', 'EG'),
('El Salvador', 'SV'),
('Guinea Ecuatorial', 'GQ'),
('Eritrea', 'ER'),
('Estonia', 'EE'),
('Etiopía', 'ET'),
('Islas Malvinas', 'FK'),
('Islas Faroe', 'FO'),
('Fiji', 'FJ'),
('Finlandia', 'FI'),
('Francia', 'FR'),
('Guyana Francesa', 'GF'),
('Polinesia Francesa', 'PF'),
('Territorios Australes Franceses', 'TF'),
('Gabón', 'GA'),
('Gambia', 'GM'),
('Georgia', 'GE'),
('Alemania', 'DE'),
('Ghana', 'GH'),
('Gibraltar', 'GI'),
('Grecia', 'GR'),
('Groenlandia', 'GL'),
('Grenada', 'GD'),
('Guadeloupe', 'GP'),
('Guam', 'GU'),
('Guatemala', 'GT'),
('Guernsey', 'GG'),
('Guinea', 'GN'),
('Guinea-Bissau', 'GW'),
('Guyana', 'GY'),
('Haiti', 'HT'),
('Islas Heard y McDonald', 'HM'),
('Ciudad del Vaticano', 'VA'),
('Honduras', 'HN'),
('Hong Kong', 'HK'),
('Hungría', 'HU'),
('Islancia', 'IS'),
('India', 'IN'),
('Indonesia', 'ID'),
('Irán', 'IR'),
('Iraq', 'IQ'),
('Irlandia', 'IE'),
('Isla del Hombre', 'IM'),
('Israel', 'IL'),
('Italia', 'IT'),
('Jamaica', 'JM'),
('Japón', 'JP'),
('Jersey', 'JE'),
('Jordán', 'JO'),
('Kazakhstán', 'KZ'),
('Kenya', 'KE'),
('Kiribati', 'KI'),
('República de Korea', 'KR'),
('Kuwait', 'KW'),
('Kyrgyzstán', 'KG'),
('República Democrática Popular de Laos', 'LA'),
('Latvia', 'LV'),
('Líbano', 'LB'),
('Lesoto', 'LS'),
('Liberia', 'LR'),
('Libia', 'LY'),
('Liechtenstein', 'LI'),
('Lituania', 'LT'),
('Luxemburgo', 'LU'),
('Macao', 'MO'),
('Macedonia', 'MK'),
('Madagascar', 'MG'),
('Malawi', 'MW'),
('Malasia', 'MY'),
('Maldivas', 'MV'),
('Mali', 'ML'),
('Malta', 'MT'),
('Islas Marshall', 'MH'),
('Martinica', 'MQ'),
('Mauritania', 'MR'),
('Mauricio', 'MU'),
('Mayotte', 'YT'),
('México', 'MX'),
('Micronesia, Federated States of', 'FM'),
('Moldova, Republic of', 'MD'),
('Monaco', 'MC'),
('Mongolia', 'MN'),
('Montenegro', 'ME'),
('Montserrat', 'MS'),
('Morocco', 'MA'),
('Mozambique', 'MZ'),
('Mianmar', 'MM'),
('Namibia', 'NA'),
('Nauru', 'NR'),
('Nepal', 'NP'),
('Países Bajos', 'NL'),
('New Caledonia', 'NC'),
('New Zealand', 'NZ'),
('Nicaragua', 'NI'),
('Niger', 'NE'),
('Nigeria', 'NG'),
('Niue', 'NU'),
('Isla de Norfolk', 'NF'),
('Islas Marianas del Norte', 'MP'),
('Noruega', 'NO'),
('Omán', 'OM'),
('Pakistán', 'PK'),
('Palau', 'PW'),
('Palestina', 'PS'),
('Panamá', 'PA'),
('Papúa Nueva Guinea', 'PG'),
('Paraguay', 'PY'),
('Perú', 'PE'),
('Filipinas', 'PH'),
('Pitcairn', 'PN'),
('Polonia', 'PL'),
('Portugal', 'PT'),
('Puerto Rico', 'PR'),
('Qatar', 'QA'),
('Reunión', 'RE'),
('Rumanía', 'RO'),
('Rusia', 'RU'),
('Ruanda', 'RW'),
('San Bartolomé', 'BL'),
('Santa Elena, Ascensión y Tristán da Cunha', 'SH'),
('San Cristóbal y Nieves', 'KN'),
('Santa Lucía', 'LC'),
('San Martín', 'MF'),
('San Pedro y Miquelón', 'PM'),
('San Vicente y las Granadinas', 'VC'),
('Samoa', 'WS'),
('San Marino', 'SM'),
('Santo Tomé y Príncipe', 'ST'),
('Arabia Saudí', 'SA'),
('Senegal', 'SN'),
('Serbia', 'RS'),
('Seychelles', 'SC'),
('Sierra Leona', 'SL'),
('Singapur', 'SG'),
('Eslovaquia', 'SK'),
('Eslovenia', 'SI'),
('Islas Salomón', 'SB'),
('Somalia', 'SO'),
('Sudáfrica', 'ZA'),
('South Georgia and the South Sandwich Islands', 'GS'),
('Sudán del Sur', 'SS'),
('España', 'ES'),
('Sri Lanka', 'LK'),
('Sudán', 'SD'),
('Surinam', 'SR'),
('Svalbard y Jan Mayen', 'SJ'),
('Esuatini', 'SZ'),
('Suecia', 'SE'),
('Suiza', 'CH'),
('República Árabe Siria', 'SY'),
('Taiwán', 'TW'),
('Tajikistán', 'TJ'),
('República Unida de Tanzania', 'TZ'),
('Tailandia', 'TH'),
('Timor-Leste', 'TL'),
('Togo', 'TG'),
('Tokelau', 'TK'),
('Tonga', 'TO'),
('Trinidad y Tobago', 'TT'),
('Tunisia', 'TN'),
('Turquía', 'TR'),
('Turkmenistán', 'TM'),
('Islas Turcas y Caicos', 'TC'),
('Tuvalu', 'TV'),
('Uganda', 'UG'),
('Ucrania', 'UA'),
('Emiratos Árabes Unidos', 'AE'),
('Reino Unido', 'GB'),
('Estados Unidos', 'US'),
('Islas periféricas menores de Estados Unidos', 'UM'),
('Uruguay', 'UY'),
('Uzbekistán', 'UZ'),
('Vanuatu', 'VU'),
('Venezuela', 'VE'),
('Vietnam', 'VN'),
('Islas Vírgenes Británicas', 'VG'),
('Islas Vírgenes, EE.UU.', 'VI'),
('Wallis y Futuna', 'WF'),
('Sahara Occidental', 'EH'),
('Yemen', 'YE'),
('Zambia', 'ZM'),
('Zimbabwe', 'ZW')