INSERT INTO states (id, name, country_id) VALUES
('EC01','Azuay','EC'),
('EC02','Bolivar','EC'),
('EC03','Cañar','EC'),
('EC04','Carchi','EC'),
('EC05','Cotopaxi','EC'),
('EC06','Chimborazo','EC'),
('EC07','El Oro','EC'),
('EC08','Esmeraldas','EC'),
('EC09','Guayas','EC'),
('EC10','Imbabura','EC'),
('EC11','Loja','EC'),
('EC12','Los Ríos','EC'),
('EC13','Manabi','EC'),
('EC14','Morona Santiago','EC'),
('EC15','Napo','EC'),
('EC16','Pastaza','EC'),
('EC17','Pichincha','EC'),
('EC18','Tungurahua','EC'),
('EC19','Zamora Chinchipe','EC'),
('EC20','Galápagos','EC'),
('EC21','Sucumbios','EC'),
('EC22','Orellana','EC'),
('EC23','Santo Domingo De Los Tsáchilas','EC'),
('EC24','Santa Elena','EC'),
('EC90','Zona No Delimitada','EC');

